language: r
cache: packages
addons:
  apt:
    packages:
    - libapparmor-dev
    - libcurl4-openssl-dev
    - openjdk-7-jre
r_github_packages:
  - r-lib/covr
  - predict-r/tikajar
after_success:
  - Rscript -e 'covr::codecov()'